name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: false

      - name: run tests
        run: go test ./...
